import React, { useState, useEffect } from 'react';
import { Container, Row, Col, Card, Table, Button, Spinner, Alert, Modal, Form, Badge } from 'react-bootstrap';
import Sidebar from '../components/Sidebar';
import { LineChart, BarChart, DoughnutChart } from '../components/Charts';
import AdminLeakageReports from '../components/AdminLeakageReports';
import api from '../services/api';
import { FaChartLine, FaCalendarAlt, FaFileInvoiceDollar, FaTint, FaMoneyBillWave, FaDownload, FaEye, FaUsers, FaPercent, FaWater, FaExclamationTriangle, FaUserPlus, FaCreditCard, FaCheckCircle } from 'react-icons/fa';

function ManagerDashboard({ user, onLogout, darkMode, toggleDarkMode }) {
  const [activePage, setActivePage] = useState('dashboard');
  const [loading, setLoading] = useState(true);
  const [dashboardData, setDashboardData] = useState(null);
  const [summaryData, setSummaryData] = useState(null);
  const [bills, setBills] = useState([]);
  const [reportData, setReportData] = useState(null);
  const [timeRange, setTimeRange] = useState('monthly');
  const [alertMsg, setAlertMsg] = useState({ show: false, message: '', variant: 'success' });
  const [customers, setCustomers] = useState([]);
  const [pendingUsers, setPendingUsers] = useState([]);
  const [payments, setPayments] = useState([]);
  const [showCustomerModal, setShowCustomerModal] = useState(false);
  const [showPaymentModal, setShowPaymentModal] = useState(false);
  const [customerForm, setCustomerForm] = useState({ userId: '', name: '', address: '', phone: '' });
  const [paymentForm, setPaymentForm] = useState({ billId: '', amount: '', paymentMethod: 'CREDIT_CARD', cardLast4: '', cardHolder: '' });
  const [selectedBill, setSelectedBill] = useState(null);
  const [unpaidBills, setUnpaidBills] = useState([]);

  useEffect(() => { fetchAll(); }, []);
  useEffect(() => { fetchForPage(); }, [activePage, timeRange]);

  const fetchAll = async () => { try { const b = await api.get('/bills/all'); setBills(b.data || []); } catch (e) {} };
  const fetchForPage = async () => {
    setLoading(true);
    try {
      if (activePage === 'dashboard') { const [dash, sum] = await Promise.all([api.get('/dashboard/manager'), api.get('/reports/dashboard-summary')]); setDashboardData(dash.data); setSummaryData(sum.data); }
      else if (activePage === 'bills') { const b = await api.get('/bills/all'); setBills(b.data || []); }
      else if (activePage === 'customers') { const [c, p] = await Promise.all([api.get('/customers/all'), api.get('/customers/pending-users')]); setCustomers(c.data || []); setPendingUsers(p.data || []); }
      else if (activePage === 'payments') { const [pay, b] = await Promise.all([api.get('/reports/all-payments'), api.get('/bills/all')]); setPayments(pay.data || []); setBills(b.data || []); setUnpaidBills((b.data || []).filter(x => x.payment_status === 'UNPAID')); }
      else { const r = await api.get(`/reports/summary?type=${activePage}`); setReportData(r.data); const s = await api.get('/reports/dashboard-summary'); setSummaryData(s.data); }
    } catch (error) { showAlert('Error loading data', 'danger'); } finally { setLoading(false); }
  };

  const showAlert = (message, variant) => { setAlertMsg({ show: true, message, variant }); setTimeout(() => setAlertMsg({ show: false }), 4000); };
  const exportCSV = () => { const rows = bills.map(b => ({ bill_number: b.bill_number, account: b.account_number, customer: b.customer_name || '', month: b.month, consumption: b.consumption, amount: b.total_amount, status: b.payment_status, due_date: b.due_date })); if (!rows.length) { showAlert('No data to export', 'warning'); return; } const headers = Object.keys(rows[0]).join(','); const csv = [headers, ...rows.map(r => Object.values(r).map(v => `"${v}"`).join(','))].join('\n'); const blob = new Blob([csv], { type: 'text/csv' }); const url = window.URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = `wasco-bills-${activePage}-${new Date().toISOString().slice(0, 10)}.csv`; a.click(); window.URL.revokeObjectURL(url); showAlert('CSV exported', 'success'); };
  const handleCreateCustomer = async () => { if (!customerForm.userId || !customerForm.name) { showAlert('User ID and Name required', 'warning'); return; } setLoading(true); try { await api.post('/customers/create', customerForm); showAlert('Customer created', 'success'); setShowCustomerModal(false); setCustomerForm({ userId: '', name: '', address: '', phone: '' }); const [c, p] = await Promise.all([api.get('/customers/all'), api.get('/customers/pending-users')]); setCustomers(c.data || []); setPendingUsers(p.data || []); } catch (e) { showAlert('Error', 'danger'); } finally { setLoading(false); } };
  const openPaymentModal = (bill) => { setSelectedBill(bill); setPaymentForm({ billId: bill.id, amount: bill.total_amount, paymentMethod: 'CREDIT_CARD', cardLast4: '', cardHolder: '' }); setShowPaymentModal(true); };
  const handleRecordPayment = async () => { if (!paymentForm.billId || !paymentForm.amount) { showAlert('Bill and amount required', 'warning'); return; } setLoading(true); try { await api.post('/bills/pay', { billId: paymentForm.billId, amount: parseFloat(paymentForm.amount), paymentMethod: paymentForm.paymentMethod, cardLast4: paymentForm.cardLast4, cardHolder: paymentForm.cardHolder }); showAlert('Payment recorded', 'success'); setShowPaymentModal(false); setPaymentForm({ billId: '', amount: '', paymentMethod: 'CREDIT_CARD', cardLast4: '', cardHolder: '' }); const [pay, b] = await Promise.all([api.get('/reports/all-payments'), api.get('/bills/all')]); setPayments(pay.data || []); setBills(b.data || []); setUnpaidBills((b.data || []).filter(x => x.payment_status === 'UNPAID')); } catch (e) { showAlert('Error', 'danger'); } finally { setLoading(false); } };

  const kpi = () => {
    const d = dashboardData; const s = summaryData;
    return [
      { title: 'Total Revenue', value: `M ${Number(s?.total_revenue || 0).toLocaleString()}`, icon: <FaMoneyBillWave size={24} />, color: 'success' },
      { title: 'Collection Rate', value: `${Number(s?.collection_rate || 0).toFixed(1)}%`, icon: <FaPercent size={24} />, color: 'info' },
      { title: 'Outstanding', value: `M ${Number(d?.outstanding?.total_outstanding || 0).toLocaleString()}`, icon: <FaFileInvoiceDollar size={24} />, color: 'warning' },
      { title: 'Total Customers', value: Number(s?.total_customers || 0).toLocaleString(), icon: <FaUsers size={24} />, color: 'primary' },
    ];
  };

  const renderKPIStats = () => (<Row className="mb-4">{kpi().map((stat, idx) => (<Col md={3} key={idx}><Card className="mb-3 h-100"><Card.Body className="d-flex justify-content-between align-items-center"><div><p className="text-muted mb-1">{stat.title}</p><h3 className="mb-0">{stat.value}</h3></div><div className={`text-${stat.color}`}>{stat.icon}</div></Card.Body></Card></Col>))}</Row>);
  const renderRevenueChart = () => { const rows = dashboardData?.monthly_revenue || []; if (!rows.length) return <Alert variant="light">No revenue data available yet.</Alert>; const data = rows.map(r => ({ month: r.month, value: Number(r.revenue) || 0 })); return (<Card className="mb-4"><Card.Header className="d-flex justify-content-between align-items-center"><h5 className="mb-0">Revenue Trend</h5><Button variant="outline-secondary" size="sm" onClick={exportCSV}><FaDownload className="me-1" />Export</Button></Card.Header><Card.Body style={{ height: '400px' }}><LineChart data={data} title="Revenue (M)" darkMode={darkMode} /></Card.Body></Card>); };
  const renderUsageChart = () => { const rows = dashboardData?.usage_trends || []; if (!rows.length) return <Alert variant="light">No usage data available yet.</Alert>; const data = rows.map(r => ({ month: r.month, value: Number(r.total_consumption || r.avg_consumption) || 0 })); return (<Card className="mb-4"><Card.Header><h5 className="mb-0">Water Consumption Trends</h5></Card.Header><Card.Body style={{ height: '350px' }}><BarChart data={data} title="Consumption (m³)" darkMode={darkMode} /></Card.Body></Card>); };
  const renderCollectionRateChart = () => { const cr = dashboardData?.collection_rate || summaryData; if (!cr) return null; const collected = Number(cr.collected || 0); const totalBilled = Number(cr.total_billed || 0); const outstanding = totalBilled - collected; const data = [{ label: 'Collected', value: collected }, { label: 'Outstanding', value: outstanding > 0 ? outstanding : 0 }]; const rate = cr.collection_rate || (totalBilled ? ((collected / totalBilled) * 100).toFixed(1) : 0); return (<Card><Card.Header><h5 className="mb-0">Collection Performance</h5></Card.Header><Card.Body style={{ height: '250px' }}><DoughnutChart data={data} title={`Rate: ${rate}%`} darkMode={darkMode} /></Card.Body></Card>); };
  const renderOutstandingBillsTable = () => { const outstanding = bills.filter(b => b.payment_status === 'UNPAID'); return (<Card className="mb-4"><Card.Header className="d-flex justify-content-between align-items-center"><h5 className="mb-0">Outstanding Bills ({outstanding.length})</h5>{outstanding.length > 10 && (<Button variant="link" size="sm" onClick={() => setActivePage('bills')}>View All <FaEye className="ms-1" /></Button>)}</Card.Header><Card.Body><Table striped hover responsive><thead><tr><th>Bill #</th><th>Account</th><th>Customer</th><th>Month</th><th>Amount</th><th>Due Date</th><th>Status</th></tr></thead><tbody>{outstanding.length === 0 ? (<tr><td colSpan="7" className="text-center text-muted">No outstanding bills</td></tr>) : outstanding.slice(0, 10).map(b => (<tr key={b.id}><td>{b.bill_number}</td><td>{b.account_number}</td><td>{b.customer_name || '-'}</td><td>{b.month ? new Date(b.month).toLocaleDateString() : '-'}</td><td className="fw-bold">M {Number(b.total_amount).toLocaleString()}</td><td className={new Date(b.due_date) < new Date() ? 'text-danger' : ''}>{b.due_date ? new Date(b.due_date).toLocaleDateString() : '-'}</td><td><span className="badge bg-danger">{b.payment_status}</span></td></tr>))}</tbody></Table></Card.Body></Card>); };
  const renderBillsPage = () => (<Card><Card.Header className="d-flex justify-content-between align-items-center"><h5 className="mb-0">All Bills Overview</h5><Button variant="outline-primary" size="sm" onClick={exportCSV}><FaDownload className="me-1" />Export CSV</Button></Card.Header><Card.Body><Table striped hover responsive><thead><tr><th>Bill #</th><th>Account</th><th>Customer</th><th>Month</th><th>Consumption</th><th>Amount</th><th>Status</th><th>Payment Date</th></tr></thead><tbody>{bills.length === 0 ? (<tr><td colSpan="8" className="text-center text-muted">No bills found</td></tr>) : bills.map(b => (<tr key={b.id}><td>{b.bill_number}</td><td>{b.account_number}</td><td>{b.customer_name || '-'}</td><td>{b.month ? new Date(b.month).toLocaleDateString() : '-'}</td><td>{b.consumption} m³</td><td className="fw-bold">M {Number(b.total_amount).toLocaleString()}</td><td><span className={`badge bg-${b.payment_status === 'PAID' ? 'success' : 'danger'}`}>{b.payment_status}</span></td><td>{b.payment_date ? new Date(b.payment_date).toLocaleDateString() : '-'}</td></tr>))}</tbody></Table></Card.Body></Card>);
  const renderCustomersPage = () => (<><div className="d-flex justify-content-between align-items-center mb-4"><h3>Customer Management</h3><Button variant="primary" onClick={() => setShowCustomerModal(true)}><FaUserPlus className="me-2" />Create Customer Profile</Button></div>{pendingUsers.length > 0 && (<Card className="mb-4 border-warning"><Card.Header className="bg-warning text-dark"><FaExclamationTriangle className="me-2" />Pending Enrollment ({pendingUsers.length})</Card.Header><Card.Body><Table striped hover responsive size="sm"><thead><tr><th>ID</th><th>Email</th><th>Full Name</th><th>Role</th><th>Created</th><th>Action</th></tr></thead><tbody>{pendingUsers.map(u => (<tr key={u.id}><td>{u.id}</td><td>{u.email}</td><td>{u.full_name || '-'}</td><td><Badge bg="info">{u.role}</Badge></td><td>{u.created_at ? new Date(u.created_at).toLocaleDateString() : '-'}</td><td><Button size="sm" variant="success" onClick={() => { setCustomerForm({ userId: u.id, name: u.full_name || u.email, address: '', phone: '' }); setShowCustomerModal(true); }}><FaUserPlus className="me-1" />Enroll</Button></td></tr>))}</tbody></Table></Card.Body></Card>)}<Card><Card.Header><h5 className="mb-0">All Customers ({customers.length})</h5></Card.Header><Card.Body><Table striped hover responsive><thead><tr><th>Account #</th><th>Name</th><th>Email</th><th>Phone</th><th>Address</th><th>Joined</th></tr></thead><tbody>{customers.length === 0 ? (<tr><td colSpan="6" className="text-center text-muted">No customers found</td></tr>) : customers.map(c => (<tr key={c.id}><td><code>{c.account_number}</code></td><td>{c.name}</td><td>{c.email || c.full_name || '-'}</td><td>{c.phone || '-'}</td><td>{c.address || '-'}</td><td>{c.created_at ? new Date(c.created_at).toLocaleDateString() : '-'}</td></tr>))}</tbody></Table></Card.Body></Card></>);
  const renderPaymentsPage = () => (<><div className="d-flex justify-content-between align-items-center mb-4"><h3>Payments</h3><Button variant="primary" onClick={() => setShowPaymentModal(true)}><FaCreditCard className="me-2" />Record Payment</Button></div>{unpaidBills.length > 0 && (<Card className="mb-4 border-danger"><Card.Header className="bg-danger text-white"><FaExclamationTriangle className="me-2" />Unpaid Bills ({unpaidBills.length})</Card.Header><Card.Body><Table striped hover responsive size="sm"><thead><tr><th>Bill #</th><th>Account</th><th>Customer</th><th>Amount</th><th>Due Date</th><th>Action</th></tr></thead><tbody>{unpaidBills.map(b => (<tr key={b.id}><td>{b.bill_number}</td><td>{b.account_number}</td><td>{b.customer_name || '-'}</td><td className="fw-bold text-danger">M {Number(b.total_amount).toLocaleString()}</td><td className={new Date(b.due_date) < new Date() ? 'text-danger fw-bold' : ''}>{b.due_date ? new Date(b.due_date).toLocaleDateString() : '-'}</td><td><Button size="sm" variant="success" onClick={() => openPaymentModal(b)}><FaCheckCircle className="me-1" />Pay</Button></td></tr>))}</tbody></Table></Card.Body></Card>)}<Card><Card.Header><h5 className="mb-0">Payment History ({payments.length})</h5></Card.Header><Card.Body><Table striped hover responsive><thead><tr><th>Transaction ID</th><th>Bill #</th><th>Customer</th><th>Account</th><th>Amount</th><th>Method</th><th>Date</th></tr></thead><tbody>{payments.length === 0 ? (<tr><td colSpan="7" className="text-center text-muted">No payments recorded</td></tr>) : payments.map(p => (<tr key={p.id}><td><code>{p.transaction_id || '-'}</code></td><td>{p.bill_number || '-'}</td><td>{p.customer_name || '-'}</td><td>{p.account_number || '-'}</td><td className="fw-bold text-success">M {Number(p.amount).toLocaleString()}</td><td><Badge bg="secondary">{p.payment_method || '-'}</Badge></td><td>{p.payment_date ? new Date(p.payment_date).toLocaleDateString() : '-'}</td></tr>))}</tbody></Table></Card.Body></Card></>);
  const getPeriodTitle = () => { const titles = { daily: 'Daily Report', weekly: 'Weekly Report', monthly: 'Monthly Report', quarterly: 'Quarterly Report', yearly: 'Yearly Report' }; return titles[activePage] || 'Analytics Dashboard'; };
  const renderReportPage = () => { const rev = (reportData?.monthly_revenue || []).map(r => ({ month: r.month, value: Number(r.revenue) || 0 })); const use = (reportData?.usage_trends || []).map(r => ({ month: r.period || r.month, value: Number(r.consumption) || 0 })); return (<><div className="d-flex justify-content-between align-items-center mb-4"><h3>{getPeriodTitle()}</h3><Button variant="primary" onClick={exportCSV}><FaDownload className="me-2" />Export CSV</Button></div>{renderKPIStats()}<Row><Col lg={12}><Card className="mb-4"><Card.Header><h5 className="mb-0">Revenue by Period</h5></Card.Header><Card.Body style={{ height: '400px' }}>{rev.length ? (<LineChart data={rev} title={`Revenue - ${getPeriodTitle()}`} darkMode={darkMode} />) : (<div className="d-flex align-items-center justify-content-center h-100 text-muted"><FaExclamationTriangle className="me-2" />No revenue data</div>)}</Card.Body></Card></Col></Row><Row><Col lg={6}><Card className="mb-4"><Card.Header><h5 className="mb-0">Consumption Trends</h5></Card.Header><Card.Body style={{ height: '300px' }}>{use.length ? (<BarChart data={use} title="Water Consumption (m³)" darkMode={darkMode} />) : (<div className="d-flex align-items-center justify-content-center h-100 text-muted"><FaWater className="me-2" />No usage data</div>)}</Card.Body></Card></Col><Col lg={6}>{renderCollectionRateChart()}</Col></Row>{renderOutstandingBillsTable()}</>); };

  const renderContent = () => {
    if (loading) { return (<div className="text-center py-5"><Spinner animation="border" variant="primary" /><p className="mt-3">Loading data...</p></div>); }
    if (activePage === 'dashboard') { return (<>{renderKPIStats()}<Row><Col lg={8}>{renderRevenueChart()}</Col><Col lg={4}>{renderCollectionRateChart()}</Col></Row>{renderUsageChart()}{renderOutstandingBillsTable()}</>); }
    if (activePage === 'bills') return renderBillsPage();
    if (activePage === 'customers') return renderCustomersPage();
    if (activePage === 'payments') return renderPaymentsPage();
    if (activePage === 'leakage-reports') return <AdminLeakageReports darkMode={darkMode} />;
    return renderReportPage();
  };

  const showPeriodPills = activePage === 'dashboard' || ['daily','weekly','monthly','quarterly','yearly'].includes(activePage);

  return (
    <div className={darkMode ? 'dark-mode' : ''} style={{ display: 'flex', minHeight: '100vh' }}>
      <Sidebar role="manager" activePage={activePage} setActivePage={setActivePage} onLogout={onLogout} darkMode={darkMode} toggleDarkMode={toggleDarkMode} />
      <div className="main-content flex-grow-1" style={{ overflowY: 'auto', maxHeight: '100vh' }}>
        <Container fluid className="py-3">
          <div className="d-flex justify-content-between align-items-center mb-4">
            <div><h2 className="mb-0">Welcome back, {user?.full_name || 'Manager'}!</h2><p className="text-muted">Real-time water billing analytics</p></div>
            <div className="text-end"><small className="text-muted">Last updated: {new Date().toLocaleString()}</small></div>
          </div>
          {alertMsg.show && (<Alert variant={alertMsg.variant} onClose={() => setAlertMsg({ show: false })} dismissible className="mb-4">{alertMsg.message}</Alert>)}
          {showPeriodPills && (<div className="mb-4 d-flex gap-2 flex-wrap">{['daily','weekly','monthly','quarterly','yearly'].map(p => (<Button key={p} variant={timeRange === p ? 'primary' : 'outline-secondary'} onClick={() => { setTimeRange(p); setActivePage(p); }} size="sm"><FaCalendarAlt className="me-1" />{p.charAt(0).toUpperCase() + p.slice(1)}</Button>))}</div>)}
          {renderContent()}
        </Container>
      </div>
      <Modal show={showCustomerModal} onHide={() => setShowCustomerModal(false)} backdrop="static"><Modal.Header closeButton><Modal.Title><FaUserPlus className="me-2" />Create Customer Profile</Modal.Title></Modal.Header><Modal.Body><Form><Form.Group className="mb-3"><Form.Label>User ID</Form.Label><Form.Control type="number" value={customerForm.userId} onChange={(e) => setCustomerForm({ ...customerForm, userId: e.target.value })} /></Form.Group><Form.Group className="mb-3"><Form.Label>Full Name</Form.Label><Form.Control type="text" value={customerForm.name} onChange={(e) => setCustomerForm({ ...customerForm, name: e.target.value })} /></Form.Group><Form.Group className="mb-3"><Form.Label>Address</Form.Label><Form.Control type="text" value={customerForm.address} onChange={(e) => setCustomerForm({ ...customerForm, address: e.target.value })} /></Form.Group><Form.Group className="mb-3"><Form.Label>Phone</Form.Label><Form.Control type="text" value={customerForm.phone} onChange={(e) => setCustomerForm({ ...customerForm, phone: e.target.value })} /></Form.Group></Form></Modal.Body><Modal.Footer><Button variant="secondary" onClick={() => setShowCustomerModal(false)}>Cancel</Button><Button variant="primary" onClick={handleCreateCustomer} disabled={loading}>{loading ? <Spinner size="sm" animation="border" /> : 'Create Profile'}</Button></Modal.Footer></Modal>
      <Modal show={showPaymentModal} onHide={() => setShowPaymentModal(false)} backdrop="static"><Modal.Header closeButton><Modal.Title><FaCreditCard className="me-2" />Record Payment</Modal.Title></Modal.Header><Modal.Body><Form><Form.Group className="mb-3"><Form.Label>Bill ID</Form.Label><Form.Control type="number" value={paymentForm.billId} onChange={(e) => setPaymentForm({ ...paymentForm, billId: e.target.value })} /></Form.Group><Form.Group className="mb-3"><Form.Label>Amount (M)</Form.Label><Form.Control type="number" step="0.01" value={paymentForm.amount} onChange={(e) => setPaymentForm({ ...paymentForm, amount: e.target.value })} /></Form.Group><Form.Group className="mb-3"><Form.Label>Payment Method</Form.Label><Form.Select value={paymentForm.paymentMethod} onChange={(e) => setPaymentForm({ ...paymentForm, paymentMethod: e.target.value })}><option value="CREDIT_CARD">Credit Card</option><option value="BANK_TRANSFER">Bank Transfer</option><option value="CASH">Cash</option><option value="MOBILE_MONEY">Mobile Money</option></Form.Select></Form.Group>{paymentForm.paymentMethod === 'CREDIT_CARD' && (<><Form.Group className="mb-3"><Form.Label>Card Last 4 Digits</Form.Label><Form.Control type="text" maxLength="4" value={paymentForm.cardLast4} onChange={(e) => setPaymentForm({ ...paymentForm, cardLast4: e.target.value })} /></Form.Group><Form.Group className="mb-3"><Form.Label>Card Holder</Form.Label><Form.Control type="text" value={paymentForm.cardHolder} onChange={(e) => setPaymentForm({ ...paymentForm, cardHolder: e.target.value })} /></Form.Group></>)}</Form></Modal.Body><Modal.Footer><Button variant="secondary" onClick={() => setShowPaymentModal(false)}>Cancel</Button><Button variant="success" onClick={handleRecordPayment} disabled={loading}>{loading ? <Spinner size="sm" animation="border" /> : 'Record Payment'}</Button></Modal.Footer></Modal>
    </div>
  );
}

export default ManagerDashboard;
